CREATE TABLE IF NOT EXISTS silver.silver_airline_on_time (
    year INTEGER,
    month INTEGER,
    carrier TEXT,
    carrier_name TEXT,
    airport TEXT,
    airport_name TEXT,
    arr_flights INTEGER,
    arr_del15 INTEGER,
    carrier_ct INTEGER,
    weather_ct INTEGER,
    nas_ct INTEGER,
    security_ct INTEGER,
    late_aircraft_ct INTEGER,
    arr_cancelled INTEGER,
    arr_diverted INTEGER,
    arr_delay DOUBLE PRECISION,
    carrier_delay DOUBLE PRECISION,
    weather_delay DOUBLE PRECISION,
    nas_delay DOUBLE PRECISION,
    security_delay DOUBLE PRECISION,
    late_aircraft_delay DOUBLE PRECISION,
    is_outlier_arr_delay INTEGER
);